version: '3.8'

services:
  lastpass-processor:
    image: ghcr.io/fragolinux/lastpass-cli:latest
    container_name: lastpass-processor
    volumes:
      - ./backup:/backup:ro
      - ./output:/output
      - ./logs:/logs
      - ./data:/data
    working_dir: /data
    entrypoint: ["/usr/local/share/lastpass-cli/contrib/lastpass-json-to-keepass.sh"]
    environment:
      - BACKUP_DIR=/backup
      - OUTPUT_DIR=/output
      - LOGS_DIR=/logs
    restart: unless-stopped
    # Uncomment to run in interactive mode for debugging
    # tty: true
    # stdin_open: true

  # Alternative service for manual operations
  lastpass-cli:
    image: ghcr.io/fragolinux/lastpass-cli:latest
    container_name: lastpass-cli-manual
    volumes:
      - ./backup:/backup
      - ./output:/output
      - ./logs:/logs
      - ./data:/data
    working_dir: /data
    entrypoint: ["/bin/bash"]
    command: ["-c", "sleep infinity"]
    profiles:
      - manual
    tty: true
    stdin_open: true

volumes:
  backup-data:
    driver: local
  output-data:
    driver: local
  logs-data:
    driver: local
  app-data:
    driver: local